tclcmd = { ...
'vsimmatlabsysobj lsm9ds1_top -t 1ns -novopt  -socket 55523;', ...
'add wave -radix hex lsm9ds1_top/*;', ...
'add wave -radix hex lsm9ds1_top/spi_commands_slave_XL_G/*;', ...
};
vsim('tclstart',tclcmd);
