set ioport_list [list \
      source_clk                 CLK_50MHZ_TO_FPGA \
      batt_int_in                BAT_HIGH_TO_FPGA \
      forced_start_in            FORCED_START_N_TO_FPGA \
      i2c_clk_io                 SDA_TO_FPGA_CPLD \
      i2c_data_io                SCL_TO_FPGA_CPLD \
      pc_statchg_in              PC_STATUS_CHG \
      pc_spi_clk                 PC_SPI_CLK \
      pc_spi_cs_out              PC_SPI_NCS \
      pc_spi_mosi_out            PC_SPI_DIN \
      pc_spi_miso_in             PC_SPI_DOUT \
      pc_flash_clk               PC_FLASH_CLK \
      pc_flash_cs_out            PC_FLASH_CS_N \
      pc_flash_data_io           PC_FLASH_DATA \
      pc_flash_dir_out           PC_FLASH_DIR \
      sdram_clk                  SDRAM_CLK \
      sdram_clk_en_out           SDRAM_CKE \
      sdram_command_out          SDRAM_command \
      sdram_mask_out             SDRAM_mask \
      sdram_bank_out             SDRAM_bank \
      sdram_addr_out             SDRAM_address \
      sdram_data_io              SDRAM_data \
      sd_clk                     SDCARD_CLK_TO_FPGA \
      sd_cmd_io                  SDCARD_CMD_TO_FPGA \
      sd_data_io                 SDCARD_DAT_TO_FPGA   \
      sdh_clk                    SDCARD_DI_CLK_TO_FPGA \
      sdh_cmd_io                 SDCARD_DI_CMD_TO_FPGA \
      sdh_data_io                SDCARD_DI_DAT_TO_FPGA   \
      gps_rx_io                  TXD_GPS_TO_FPGA \
      gps_tx_out                 RXD_GPS_TO_FPGA \
      gps_timemark_out           EXTINT_GPS_TO_FPGA \
      gps_timepulse_io           TIMEPULSE_GPS_TO_FPGA \
      ms_clk                     IM2_SPI_SCLK \
      ms_mosi_out                IM2_SPI_SDI \
      ms_cs_accgyro_out          IM2_CS_AG \
      ms_miso_accgyro_io         IM2_SDO_AG \
      ms_int1_accgyro_io         IM2_INT1_AG \
      ms_int2_accgyro_io         IM2_INT2_AG \
      ms_cs_mag_out              IM2_CS_M \
      ms_miso_mag_io             IM2_SDO_M \
      ms_int_mag_io              IM2_INT_M \
      ms_drdy_mag_io             IM2_DRDY_M \
      magram_clk                 MRAM_SCLK_TO_FPGA \
      magram_cs_out              MRAM_CS_N_TO_FPGA \
      magram_mosi_out            MRAM_SI_TO_FPGA \
      magram_miso_io             MRAM_SO_TO_FPGA \
      magram_writeprot_out       MRAM_WP_N_TO_FPGA \
      mic_clk                    MIC_CLK \
      mic_right_io               MIC_DATA_R \
      mic_left_io                MIC_DATA_L \
      radio_clk                  DATA_TX_DAT_TO_FPGA  \
      radio_data_io              DATA_TX_DAT_TO_FPGA ]
