----------------------------------------------------------------------------
--
--! @file       Collar Events_pkg.vhd
--! @brief      Events that can be generated by collar components.
--! @details    Information about collar events.
--! @author     Emery Newlon
--! @date       August 2014
--! @copyright  Copyright (C) 2014 Ross K. Snider and Emery L. Newlon
--
--  This program is free software: you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation, either version 3 of the License, or
--  (at your option) any later version.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
--  Emery Newlon
--  Electrical and Computer Engineering
--  Montana State University
--  610 Cobleigh Hall
--  Bozeman, MT 59717
--  emery.newlon@msu.montana.edu
--
----------------------------------------------------------------------------

package Collar_Events_pkg is

  type Collar_Events is (
  
    --  Power On/Off events.
    
    CE_MainPowerSwitchOn_e,
    CE_MainPowerSwitchOff_e,
    CE_RechargeSwitchOn_e,
    CE_RechargeSwitchOff_e,
    CE_SolarCtlShutdownOn_e,
    CE_SolarCtlShutdownOff_e,
    CE_LevelShifter3p3On_e,
    CE_LevelShifter3p3Off_e,
    CE_LevelShifter1p8On_e,
    CE_LevelShifter1p8Off_e,
    CE_InertialOn1p8_e,
    CE_InertialOff2p5_e,
    CE_MicLeftOn_e,
    CE_MicLeftOff_e,
    CE_MicRightOn_e,
    CE_MicRightOff_e,
    CE_SDRAM_On_e,
    CE_SDRAM_Off_e,
    CE_SDCardOn_e,
    CE_SDCardOff_e,
    CE_GPS_On_e,
    CE_GPS_Off_e,
    CE_DataTX_On_e,
    CE_DataTX_Off_e,

    --  Power Controller Status events.
    
    CE_BatteryGoodOn_e,
    CE_BatteryGoodOff_e,
    CE_SolarCtlOn_e,
    CE_SolarCtlOff_e,
    CE_BattMonLowOn_e,
    CE_BattMonLowOff_e,
    CE_ForceStartupOn_e,
    CE_ForceStartupOff_e,
    CE_PwrGood2p5On_e,
    CE_PwrGood2p5Off_e,
    CE_PwrGood3p3On_e,
    CE_PwrGood3p3Off_e

  ) ;

  constant collar_event_cnt_c     : natural :=
      Collar_Events'pos(Collar_Events'high) + 1 ;

end package Collar_Events_pkg ;
