----------------------------------------------------------------------------
--
--! @file       Collar Events_pkg.vhd
--! @brief      Events that can be generated by collar components.
--! @details    Information about collar events.
--! @author     Emery Newlon
--! @date       August 2014
--! @copyright  Copyright (C) 2014 Ross K. Snider and Emery L. Newlon
--
--  This program is free software: you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation, either version 3 of the License, or
--  (at your option) any later version.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
--  Emery Newlon
--  Electrical and Computer Engineering
--  Montana State University
--  610 Cobleigh Hall
--  Bozeman, MT 59717
--  emery.newlon@msu.montana.edu
--
----------------------------------------------------------------------------

package Collar_Events_pkg is

  type Collar_Events is (
    AUDIO_CAPTURE_ERROR,
    AUDIO_OUTPUT_ERROR
  ) ;

  constant collar_event_cnt_c     : natural :=
      Collar_Events'pos(Collar_Events'high) + 1 ;

end package Collar_Events_pkg ;
