set ioport_list [list \
      source_clk                 CLK_50MHZ_TO_FPGA \
      batt_int_in                FPGA_BATT_INT \
      forced_start_in            FORCE_STARTUP_TO_FPGA \
      i2c_clk_io                 I2C_SDA \
      i2c_data_io                I2C_SCL \
      pc_statchg_in              PC_STATUS_CHANGED \
      pc_spi_clk                 PC_SPI_CLK \
      pc_spi_cs_out              PC_SPI_NCS \
      pc_spi_mosi_out            PC_SPI_DIN \
      pc_spi_miso_in             PC_SPI_DOUT \
      pc_flash_clk               FLASH_C \
      pc_flash_cs_out            FLASH_S_N \
      pc_flash_data_io           PC_FLASH_DATA \
      pc_flash_dir_out           PC_FLASH_DIR \
      sdram_clk                  SDRAM_CLK \
      sdram_clk_en_out           SDRAM_CKE \
      sdram_command_out          SDRAM_command \
      sdram_mask_out             SDRAM_mask \
      sdram_bank_out             SDRAM_bank \
      sdram_addr_out             SDRAM_address \
      sdram_data_io              SDRAM_data \
      sdh_clk                    SDCARD_DI_CLK_TO_FPGA \
      sdh_cmd_io                 SDCARD_DI_CMD_TO_FPGA \
      sdh_data_io                SDCARD_DI_DAT_TO_FPGA  \
      gps_rx_io                  TXD_GPS_TO_FPGA \
      gps_tx_out                 RXD_GPS_TO_FPGA \
      gps_timemark_out           EXTINT_GPS_TO_FPGA \
      gps_timepulse_io           TIMEPULSE_GPS_TO_FPGA \
      ms_clk                     IM_SPI_SCLK_TO_FPGA \
      ms_mosi_out                IM_SPI_SDI_TO_FPGA \
      ms_cs_accgyro_out          IM_CS_A_G_TO_FPGA \
      ms_miso_accgyro_io         IM_SDO_A_G_TO_FPGA \
      ms_int1_accgyro_io         IM_INT1_A_G_TO_FPGA \
      ms_int2_accgyro_io         IM_INT2_A_G_TO_FPGA \
      ms_cs_mag_out              IM_CS_M_TO_FPGA \
      ms_miso_mag_io             IM_SDO_M_TO_FPGA \
      ms_int_mag_io              IM_INT_M_TO_FPGA \
      ms_drdy_mag_io             IM_DRDY_M_TO_FPGA \
      magram_clk                 MRAM_SCK_TO_FPGA \
      magram_cs_out              MRAM_CS_N_TO_FPGA \
      magram_mosi_out            MRAM_SI_TO_FPGA \
      magram_miso_io             MRAM_SO_TO_FPGA \
      magram_writeprot_out       MRAM_WP_N_TO_FPGA \
      mic_clk                    MIC_CLK_TO_FPGA \
      mic_right_io               MIC_B_DATA_TO_FPGA \
      mic_left_io                MIC_A_DATA_TO_FPGA ]
