%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\s58p233\Dropbox\SummerWork2015\WirelessData\20150724Data\NPreampOrientation.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/07/27 14:08:45

%% Initialize variables.
filename = 'C:\Users\s58p233\Dropbox\SummerWork2015\WirelessData\20150724Data\NPreampOrientation.dat';
delimiter = {',',' '};

%% Format string for each line of text:
%   column3: double (%f)
%	column7: double (%f)
%   column11: double (%f)
%	column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%*s%*s%*s%f%*s%*s%*s%f%*s%*s%*s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
NPreampCounterVal = dataArray{:, 1};
NPreampX = dataArray{:, 2};
NPreampY = dataArray{:, 3};
NPreampZ = dataArray{:, 4};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;