%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\tyler.davis5\Dropbox\SummerWork2015\WirelessData\LunchRun.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/06/26 10:58:24

%% Initialize variables.
filename = 'C:\Users\tyler.davis5\Dropbox\SummerWork2015\WirelessData\LunchRun.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: date strings (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%s%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Convert the contents of column with dates to serial date numbers using date format string (datenum).
dataArray{8} = datenum(dataArray{8}, 'HH:MM:SS');

%% Allocate imported array to column variable names
LunchLatitude = dataArray{:, 5};
LunchLongitude = dataArray{:, 6};
LunchTime = dataArray{:, 8};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;